name: Trigger auto deployment for capp-ichthyo-cup

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Dockerfile.production/**'
    - '.github/workflows/capp-ichthyo-cup-AutoDeployTrigger-3020c097-10d5-49b3-9245-2e3d8e3f1e2a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: crichtyocup.azurecr.io
          username: ${{ secrets.CAPPICHTHYOCUP_REGISTRY_USERNAME }}
          password: ${{ secrets.CAPPICHTHYOCUP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: crichtyocup.azurecr.io/capp-ichthyo-cup:${{ github.sha }}
          file: ./Dockerfile.production/Dockerfile
          context: ./Dockerfile.production/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPICHTHYOCUP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n capp-ichthyo-cup -g rg-ichthyo-cup --server crichtyocup.azurecr.io --username  ${{ secrets.CAPPICHTHYOCUP_REGISTRY_USERNAME }} --password ${{ secrets.CAPPICHTHYOCUP_REGISTRY_PASSWORD }}
            az containerapp update -n capp-ichthyo-cup -g rg-ichthyo-cup --image crichtyocup.azurecr.io/capp-ichthyo-cup:${{ github.sha }}
